#!/usr/bin/env bash

set -e
# shellcheck disable=SC3040
set -o pipefail

cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd)"
# shellcheck source=script/utils/resolve_secrets.sh
. "$SCRIPT_DIR"/utils/resolve_secrets.sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

script/utils/launch-docker.sh

echo "==> Installing application dependencies..."

nodenv install --skip-existing
npm install

echo "==> Installing E2E testing dependencies..."
npx playwright install

echo "script dir $SCRIPT_DIR"

echo "==> Creating .env file and resolving secrets"

secret_names=("hmpps-cas-test-users")
resolve_secrets "$SCRIPT_DIR/../.env.template" \
                "$SCRIPT_DIR/../.env" \
                "hmpps-community-accommodation-dev" \
                "${secret_names[@]}"