#!/bin/sh

# script/generate-types: Generates typescript types from the OpenApi spec in the API repo

set -e

cd "$(dirname "$0")/.."

echo "==> Generating types..."

npx openapi-typescript-codegen -i https://raw.githubusercontent.com/ministryofjustice/hmpps-approved-premises-api/1c3262819d5b9020b0a6c7619480c5691dc63d76/src/main/resources/static/codegen/built-cas2-api-spec.yml -o ./server/@types/shared -c axios --exportServices false --exportCore false --useUnionTypes true

echo "==> Renaming the declaration file..."

mv ./server/@types/shared/index.ts ./server/@types/shared/index.d.ts


