#!/bin/sh

# script/generate-types: Generates typescript types from the OpenApi spec in the API repo

set -e

cd "$(dirname "$0")/.."

if [ -z "$1" ]; then
  url="https://approved-premises-api-dev.hmpps.service.justice.gov.uk/v3/api-docs/CAS2"
else
  url=$1
fi

echo "==> Generating types using: $url"

npx openapi-typescript-codegen -i "$url" -o ./server/@types/shared -c axios --exportServices false --exportCore false --useUnionTypes true

echo "==> Renaming the declaration file..."

mv ./server/@types/shared/index.ts ./server/@types/shared/index.d.ts


