#!/bin/sh

SPLIT_INDEX=$1
SPLIT_TOTAL=$2

export TESTS="$(find integration_tests -type f -name "*.cy.ts" | \
    awk -v splitTotal=$SPLIT_TOTAL -v splitIndex=$SPLIT_INDEX 'NR % splitTotal == splitIndex % splitTotal' | \
    tr '\n' ',' | sed 's/,$//')"

echo "test-suite=$TESTS" >> "$GITHUB_OUTPUT"
