#!/bin/sh

# script/test: Run the test suite for the application.

set -e

echo "==> Linting the code"

npm run lint

echo "==> Typechecking the code"

npm run typecheck

echo "==> Running unit tests..."

npm run test

echo "==> Starting the backing services in Docker..."

script/utils/launch-docker.sh
docker-compose -f docker-compose-test.yml up -d

echo "==> Running integration tests..."

npm run test:integration

echo "==> Running security audit"

npm run security_audit

