name: CAS2 UI E2E tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  e2e_test:
    name: "CAS2 E2E Tests 🧪"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [ 1, 2 ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Repository is specified to run the workflow from the API repository
          repository: 'ministryofjustice/hmpps-community-accommodation-tier-2-ui'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run E2E Tests
        env:
          CAS2_HMPPS_AUTH_USERNAME: ${{ secrets.E2E_USER_CAS2_HMPPS_AUTH_USERNAME }}
          CAS2_HMPPS_AUTH_PASSWORD: ${{ secrets.E2E_USER_CAS2_HMPPS_AUTH_PASSWORD }}
          CAS2_ADMIN_USERNAME: ${{ secrets.E2E_USER_CAS2_ADMIN_USERNAME }}
          CAS2_ADMIN_PASSWORD: ${{ secrets.E2E_USER_CAS2_ADMIN_PASSWORD }}
          CAS2_ASSESSOR_USERNAME: ${{ secrets.E2E_USER_CAS2_ASSESSOR_USERNAME }}
          CAS2_ASSESSOR_PASSWORD: ${{ secrets.E2E_USER_CAS2_ASSESSOR_PASSWORD }}
          CAS2_MI_USERNAME: ${{ secrets.E2E_USER_CAS2_MI_USERNAME }}
          CAS2_MI_PASSWORD: ${{ secrets.E2E_USER_CAS2_MI_PASSWORD }}
          CAS2_LCA_USERNAME: ${{ secrets.E2E_USER_CAS2_LCA_USERNAME }}
          CAS2_LCA_PASSWORD: ${{ secrets.E2E_USER_CAS2_LCA_PASSWORD }}
        run: npm run test:e2e -- --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: CAS2-E2E-playwright-report-${{ matrix.shard }}-of-${{ strategy.job-total }}
          path: playwright-report
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload E2E artefacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: CAS2-E2E-artefacts-${{ matrix.shard }}-of-${{ strategy.job-total }}
          path: test-results
          retention-days: 30
          if-no-files-found: ignore

  e2e_test_notify_slack:
    name: "E2E test failure notification"
    needs: e2e_test
    if: ${{ always() && needs.e2e_test.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: ministryofjustice/hmpps-community-accommodation-tier-2-ui/.github/actions/slack_failure_notification@main
        with:
          title: "CAS2 E2E Tests"
          job: "e2e_test"
          channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
