name: Generate Types

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

env:
  NODE_ENV: test
  API_CLIENT_ID: approved-premises
  API_CLIENT_SECRET: clientsecret

jobs:
  generate-types:
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # V6.0.2
        with:
          # Repository is specified to run the workflow from the API repository
          repository: 'ministryofjustice/hmpps-community-accommodation-tier-2-ui'

      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # V6.3.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Generate Token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            hmpps-community-accommodation-tier-2-ui

      - name: Generate Types
        run: ./script/generate-types ${{ vars.CAS2_API_SPEC_URL }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # V8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: 'API model updates'
          commit-message: 'Updating hmpps-approved-premises-api models from OpenAPI specification'
          body: 'Updating hmpps-approved-premises-api models from OpenAPI specification.  This PR was created automatically from the generate-types.yml Workflow'
          delete-branch: true
          branch: update-api-types
