name: Security veracode pipeline scan

on:
  workflow_dispatch:
  schedule:
    - cron: "16 4 * * MON-FRI" # Every weekday at 04:16 UTC

jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@8d9c52e65720e36d445d9611f68ca4afd8494526 # v2.14.3
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
