name: Security veracode pipeline scan

on:
  workflow_dispatch:
  schedule:
    - cron: "16 4 * * MON-FRI" # Every weekday at 04:16 UTC

jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@8de783c7b6dc61ad8ba384924dc1fe93098d9995 # 2.13.1
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
